title: Tongxin Wang
url: "https://txwang.github.io"
baseurl: "/"

markdown: kramdown

tracking_id: #

footer: yes
footer_url: "https://txwang.github.io/"
footer_text: "Last Updated: 05/04/2020 by Tongxin Wang."

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Contact"
   link: "contact"
 - name: "Resume"
   link: "Resume_Tongxin_Wang.pdf"
 - name: "About"
   link: "/"
